### ISSUE TITLE
Compare To... with a file doesn't show comparison

### ISSUE THREAD

**Issue by Sharlikran** [TES5Edit/TES5Edit#517]
![image](https://user-images.githubusercontent.com/1912426/44025725-bcea18da-9ea5-11e8-9fa2-f24128291abf.png)

When I load a mod, then use COmpare To... I expect to see the two mods records compared it two columns when they share records with the same FormID so I can compare changes.

**Comment by Sharlikran** [comment]
Using 3.2.1 I chose the same two records and chose compare selected. Then I see what i expected.

![image](https://user-images.githubusercontent.com/1912426/44026377-b2f3da1c-9ea7-11e8-94be-8182c5d7f2f0.png)

**Comment by Sharlikran** [comment]
With 3.2.29 I noticed that the header compares but not the records

![image](https://user-images.githubusercontent.com/1912426/44027258-a90a21a2-9eaa-11e8-8533-91a71b5f1772.png)

**Comment by eFrysTon** [comment]
no they don't because they  have different FormIDs inside the file
and yes, that's probably something that should be fixed

**Comment by Sharlikran** [comment]
![image](https://user-images.githubusercontent.com/1912426/44027706-4960f8f0-9eac-11e8-91a7-28dac9817771.png)

Took a while, they are the same now.

![image](https://user-images.githubusercontent.com/1912426/44027714-56a8adfa-9eac-11e8-991a-6bc43968c91c.png)

Still not comparing.

[Revolution_Clothing_test.zip](https://github.com/TES5Edit/TES5Edit/files/2282673/Revolution_Clothing_test.zip)

**Comment by Sharlikran** [comment]
Needs [SKE](https://www.nexusmods.com/fallout4/mods/12226)
[Armorsmith Extended](https://www.nexusmods.com/fallout4/mods/2228)
[AWKCR](https://www.nexusmods.com/fallout4/mods/6091)

**Comment by Sharlikran** [comment]
When I do compare selected the first time before resizing the columns, I have three columns, see the this one on the far right?

![image](https://user-images.githubusercontent.com/1912426/44027977-46043324-9ead-11e8-8978-c409945a89e2.png)

That's with Fit All

![image](https://user-images.githubusercontent.com/1912426/44028008-59fbe2f0-9ead-11e8-9e5c-0ab34278821d.png)

I expand the third one.

Once I expand them to where the thrid one scrolls off the edge of the viewable area it disappears.

![image](https://user-images.githubusercontent.com/1912426/44028050-77cff94c-9ead-11e8-9134-81130727f14a.png)

**Comment by Sharlikran** [comment]
Copy another file and it works fine.

![image](https://user-images.githubusercontent.com/1912426/44028144-d01a84dc-9ead-11e8-8ea9-c7846f2d2f8b.png)

**Comment by Sharlikran** [comment]
I can close this, if you want, but the AV for not specifying a filename is odd, and the third column was weird too. So I'll leave it open for now.
